name: docs_PR_testing
on:
  pull_request_target:
    branches:
     - master
    paths:
      - 'docs/**'
jobs :
   Docs1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: docs
        if: ${{github.event_name == 'pull_request' ||'push' || startsWith(github.ref, 'refs/tags/v')}}
        env: 
         VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
         GITHUB_TOKEN: ${{secrets.PAT_TOKEN }} 
         
#          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
#          GITHUB_EVENT_AFTER: ${{ github.event.after }}
         
#          COMMIT_RANGE: ${{ github.event.pull_request.base.ref }}...${{ github.event.pull_request.base.sha }}
#          GITHUB_CONTEXT: ${{ toJson(github.event) }}




#          SHA: ${{ github.sha }}
#          PULL_REQUEST_SHA: ${{ github.event.pull_request.head.sha }}
#          MASTER_BRANCH: ${{ github.event.pull_request.base.ref }}
#          PULL_REQUEST: ${{ github.event.pull_request.head.ref }}



#          PR1: ${{ github.event.pull_request.base.ref }}
#          PR2: ${{ github.event.pull_request.base.sha }}


#          FROM_BRANCH: ${{ github.event.pull_request.base.ref }} 
#          TO_BRANCH: ${{ github.event.pull_request.head.ref }}



#         COMMIT_DIFF1: ${{ git log --cherry-pick --format="%h" --merges --left-only $TO_BRANCH...$FROM_BRANCH }}
         # GITHUB_EVENT_BEFORE: ${{ github.event.pull_request.base.ref }}
         # GITHUB_EVENT_AFTER: ${{ github.event.pull_request.base.sha }}
#           COMMIT_RANGE: ${{ github.event.pull_request.base.ref}}...${{ github.event.pull_request.base.sha }}
#            GITHUB_EVENT_BEFORE: ${{ github.event.before }}
#            GITHUB_EVENT_AFTER: ${{ github.event.after }}
#            COMMIT_RANGE: ${{ github.event.before}}...${{ github.event.after}}
#              GITHUB_diff_url: ${{ github.event.diff_url }}
        run: |
             git diff HEAD^^..HEAD -- ./docs
             git log --cherry-pick --format="%h" --merges --left-only $TO_BRANCH...$FROM_BRANCH
             touch .env
             echo "COMMIT_RANGE=($COMMIT_RANGE)" > .env
             source ci/env.sh
             .travis/channel_restriction.sh edge beta master || exit 0
             .travis/affects.sh docs/ .travis || exit 0
             cd docs/
             source .travis/before_install.sh
             source .travis/script.sh
      - name: setup-node
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-2  
